### PR TITLE
reformated code with Black

### PR DESCRIPTION
**Pull request by x0nix**
https://github.com/psf/black

### CODE REVIEW

**Review by Snakeyyy — COMMENTED** [review]
I think using black is a good idea.

But I would vote for incorporating the black autoformatting into the development process using https://pre-commit.com/ . I can do that if you want as we have this setup on other projects.

**Comment by x0nix** [comment]
> But I would vote for incorporating the black autoformatting into the development process using https://pre-commit.com/ . I can do that if you want as we have this setup on other projects.

Great, please do that.

**Comment by Snakeyyy** [comment]
> > But I would vote for incorporating the black autoformatting into the development process using https://pre-commit.com/ . I can do that if you want as we have this setup on other projects.
> 
> Great, please do that.

Done. I've set the line length for black to 119 chars as I believe 80 chars which are default is unnecessarily short.

**Comment by Snakeyyy** [comment]
@x0nix  I didn't choose the line length randomly, it was based on [Django Python style documentation](https://docs.djangoproject.com/en/3.2/internals/contributing/writing-code/coding-style/) for version 3.2:

> An exception to [PEP 8](https://peps.python.org/pep-0008/) is our rules on line lengths. Don’t limit lines of code to 79 characters if it means the code looks significantly uglier or is harder to read. We allow up to 119 characters as this is the width of GitHub code review; anything longer requires horizontal scrolling which makes review more difficult. This check is included when you run flake8. Documentation, comments, and docstrings should be wrapped at 79 characters, even though [PEP 8](https://peps.python.org/pep-0008/) suggests 72.

However, I didn't notice that the guideline changed since version 4.0 as they switched to black. 

Therefore I agree with you and let's keep the default.

**Pull request merged**
